version: ~> 1.0

env:
  global:
    # The name of the conda package
    - CONDA_PACKAGE="psdaq_control_minimal"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"

# If not using the standard-python-conda above please uncomment the required
# (language, os, dist and stages) and optional (import statements) entries from
# the blocks below.
#
language: python
os: linux
dist: xenial

stages:
  - build
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

import:
  # Build Stage
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-build.yml
  # Deploy Stage
  #- pcdshub/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml

# Add a build stage for our special version setting
jobs:
  include:
      - stage: build
        name: "Anaconda Build"
        before_script:
          - echo "Setting the version"
          - pushd conda-recipe
          - ./finalize_version.sh
          - popd

