{% set version = "CI_VERSION" %}

package:
    name    : psdaq_control_minimal
    version : {{ version.split('-')[0] }}

source:
  git_url: https://github.com/slac-lcls/lcls2.git
  git_rev: {{ version.split('-')[0] }}

  patches:
    - setup.patch

build:
    number: {{ version.split('-')[1] }}
    noarch: python
    script: {{ PYTHON }} -m pip install ./psdaq -vv

requirements:
    build:
      - python >=3.6
      - pip
    run:
      - python >=3.6
      - bluesky
      - ophyd
      - zeromq

test:
    imports:
      - psdaq.control.BlueskyScan
      - psdaq.control.ControlDef
      - psdaq.control.DaqControl

about:
  home: https://github.com/pcdshub/psdaq-control-minimal
  license: SLAC Open License
  summary: A simple repackaging of the lcls2 daq code with minimal dependencies needed for daq control in hutch python.
